"""
Internal coordinate parameters for DNA forms A, B, and Z.

Extracted from Colin's 3DNA fiber diffraction structures.
These parameters define the backbone geometry for building DNA
using the Z-matrix (internal coordinate) method.

Backbone torsion angles:
  alpha:   O3'(i-1) - P(i)   - O5'(i) - C5'(i)
  beta:    P(i)     - O5'(i) - C5'(i)  - C4'(i)
  gamma:   O5'(i)   - C5'(i) - C4'(i)  - C3'(i)
  delta:   C5'(i)   - C4'(i) - C3'(i)  - O3'(i)
  epsilon: C4'(i)   - C3'(i) - O3'(i)  - P(i+1)
  zeta:    C3'(i)   - O3'(i) - P(i+1)  - O5'(i+1)
  chi_pur: O4'     - C1'    - N9      - C4  (purines)
  chi_pyr: O4'     - C1'    - N1      - C2  (pyrimidines)

Auto-generated by extract_internal_coords.py
"""

B_DNA_PARAMS = {
    "torsion_angles": {
        "alpha": 29.9,
        "beta": -136.3,
        "chi_pur": 98.0,
        "chi_pyr": 98.0,
        "delta": -143.4,
        "epsilon": 140.8,
        "gamma": -31.1,
        "zeta": 160.5,
        # Sugar ring dihedrals (using out-of-ring references for proper closure)
        "O5'-C5'-C4'-O4'": 88.1,    # O4' placement
        "C5'-C4'-C3'-C2'": 100.7,   # C2' placement
        "C4'-C3'-C2'-C1'": 40.2,    # C1' placement (endocyclic nu2)
        # Phosphate oxygen dihedrals
        "C5'-O5'-P-O1P": -85.9,     # OP1 placement
        "C5'-O5'-P-O2P": 145.6,     # OP2 placement
    },
    "bond_lengths": {
        "C1'-N1": 1.49,
        "C1'-N9": 1.49,
        "C1'-O4'": 1.419,
        "C2'-C1'": 1.525,
        "C3'-C2'": 1.529,
        "C3'-O3'": 1.423,
        "C4'-C3'": 1.528,
        "C4'-O4'": 1.457,
        "C5'-C4'": 1.516,
        "O3'-P": 1.601,
        "O5'-C5'": 1.44,
        "P-O1P": 1.48,
        "P-O2P": 1.479,
        "P-O5'": 1.6,
    },
    "bond_angles": {
        "C1'-C2'-C3'": 96.6,
        "C2'-C1'-N1": 113.7,
        "C2'-C1'-N9": 113.7,
        "C2'-C3'-C4'": 104.7,
        "C3'-C4'-O4'": 103.9,
        "C3'-O3'-P+": 119.0,
        "C4'-C3'-O3'": 108.9,
        "C4'-O4'-C1'": 108.4,
        "C5'-C4'-C3'": 115.8,
        "C5'-C4'-O4'": 112.4,
        "O1P-P-O2P": 116.0,
        "O1P-P-O5'": 109.6,
        "O2P-P-O5'": 109.6,
        "O3'-P-O1P": 109.6,
        "O3'-P-O2P": 109.6,
        "O3'-P-O5'": 101.4,
        "O4'-C1'-C2'": 105.2,
        "O4'-C1'-N1": 108.1,
        "O4'-C1'-N9": 108.1,
        "O5'-C5'-C4'": 110.0,
        "P-O5'-C5'": 119.0,
    },
    "sugar_pucker": {
        "P": -26.1,
        "tau_m": 44.8,
    },
}

A_DNA_PARAMS = {
    "torsion_angles": {
        "alpha": 51.7,
        "beta": -174.8,
        "chi_pur": 157.2,
        "chi_pyr": 157.2,
        "delta": -79.1,
        "epsilon": 147.8,
        "gamma": -41.7,
        "zeta": 75.1,
        # Sugar ring dihedrals (using out-of-ring references)
        "O5'-C5'-C4'-O4'": 74.8,
        "C5'-C4'-C3'-C2'": 159.3,
        "C4'-C3'-C2'-C1'": -44.0,
        # Phosphate oxygen dihedrals (A-DNA specific)
        "C5'-O5'-P-O1P": -64.1,
        "C5'-O5'-P-O2P": 167.5,
    },
    "bond_lengths": {
        "C1'-N1": 1.49,
        "C1'-N9": 1.49,
        "C1'-O4'": 1.418,
        "C2'-C1'": 1.525,
        "C3'-C2'": 1.527,
        "C3'-O3'": 1.421,
        "C4'-C3'": 1.529,
        "C4'-O4'": 1.457,
        "C5'-C4'": 1.515,
        "O3'-P": 1.6,
        "O5'-C5'": 1.441,
        "P-O1P": 1.48,
        "P-O2P": 1.48,
        "P-O5'": 1.599,
    },
    "bond_angles": {
        "C1'-C2'-C3'": 101.0,
        "C2'-C1'-N1": 113.7,
        "C2'-C1'-N9": 113.7,
        "C2'-C3'-C4'": 99.0,
        "C3'-C4'-O4'": 103.9,
        "C3'-O3'-P+": 118.9,
        "C4'-C3'-O3'": 111.8,
        "C4'-O4'-C1'": 109.3,
        "C5'-C4'-C3'": 115.8,
        "C5'-C4'-O4'": 108.7,
        "O1P-P-O2P": 115.9,
        "O1P-P-O5'": 109.7,
        "O2P-P-O5'": 109.6,
        "O3'-P-O1P": 109.6,
        "O3'-P-O2P": 109.6,
        "O3'-P-O5'": 101.4,
        "O4'-C1'-C2'": 105.7,
        "O4'-C1'-N1": 109.0,
        "O4'-C1'-N9": 109.0,
        "O5'-C5'-C4'": 110.0,
        "P-O5'-C5'": 119.0,
    },
    "sugar_pucker": {
        "P": -172.1,
        "tau_m": 44.5,
    },
}

# Z-DNA has a dinucleotide repeat with alternating conformations
# pos1 = syn (even index), pos2 = anti (odd index)

Z_DNA_POS1_PARAMS = {
    "torsion_angles": {
        "alpha": -52.0,
        "beta": -179.0,
        "chi_pur": -58.5,
        "chi_pyr": -58.5,
        "delta": -94.9,
        "epsilon": 103.6,
        "gamma": 173.8,
        "zeta": 64.8,
        # Sugar ring dihedrals
        "O5'-C5'-C4'-O4'": -68.8,
        "C5'-C4'-C3'-C2'": 143.1,
        "C4'-C3'-C2'-C1'": -21.1,
        # Phosphate oxygen dihedrals (Z-DNA specific)
        "C5'-O5'-P-O1P": 63.9,
        "C5'-O5'-P-O2P": -167.7,
    },
    "bond_lengths": {
        "C1'-N1": 1.524,
        "C1'-N9": 1.517,
        "C1'-O4'": 1.418,
        "C2'-C1'": 1.525,
        "C3'-C2'": 1.528,
        "C3'-O3'": 1.422,
        "C4'-C3'": 1.529,
        "C4'-O4'": 1.458,
        "C5'-C4'": 1.516,
        "O3'-P": 1.6,
        "O5'-C5'": 1.44,
        "P-O1P": 1.48,
        "P-O2P": 1.48,
        "P-O5'": 1.6,
    },
    "bond_angles": {
        "C1'-C2'-C3'": 104.4,
        "C2'-C1'-N1": 113.2,
        "C2'-C1'-N9": 113.2,
        "C2'-C3'-C4'": 105.5,
        "C3'-C4'-O4'": 104.8,
        "C3'-O3'-P+": 119.0,
        "C4'-C3'-O3'": 111.9,
        "C4'-O4'-C1'": 111.6,
        "C5'-C4'-C3'": 115.8,
        "C5'-C4'-O4'": 108.5,
        "O1P-P-O2P": 116.0,
        "O1P-P-O5'": 109.6,
        "O2P-P-O5'": 109.6,
        "O3'-P-O1P": 109.6,
        "O3'-P-O2P": 109.6,
        "O3'-P-O5'": 101.4,
        "O4'-C1'-C2'": 108.1,
        "O4'-C1'-N1": 107.5,
        "O4'-C1'-N9": 107.5,
        "O5'-C5'-C4'": 110.0,
        "P-O5'-C5'": 119.0,
    },
    "sugar_pucker": {
        "P": -152.5,
        "tau_m": 23.8,
    },
}

Z_DNA_POS2_PARAMS = {
    "torsion_angles": {
        "alpha": 139.5,
        "beta": 136.8,
        "chi_pur": 154.2,
        "chi_pyr": 154.2,
        "delta": -137.6,
        "epsilon": 96.5,
        "gamma": -50.9,
        "zeta": -82.0,
        # Sugar ring dihedrals
        "O5'-C5'-C4'-O4'": 69.2,
        "C5'-C4'-C3'-C2'": 106.2,
        "C4'-C3'-C2'-C1'": 31.4,
        # Phosphate oxygen dihedrals (Z-DNA specific)
        "C5'-O5'-P-O1P": -104.7,
        "C5'-O5'-P-O2P": 23.8,
    },
    "bond_lengths": {
        "C1'-N1": 1.474,
        "C1'-N9": 1.468,
        "C1'-O4'": 1.418,
        "C2'-C1'": 1.525,
        "C3'-C2'": 1.528,
        "C3'-O3'": 1.422,
        "C4'-C3'": 1.529,
        "C4'-O4'": 1.456,
        "C5'-C4'": 1.516,
        "O3'-P": 1.6,
        "O5'-C5'": 1.44,
        "P-O1P": 1.48,
        "P-O2P": 1.48,
        "P-O5'": 1.6,
    },
    "bond_angles": {
        "C1'-C2'-C3'": 101.7,
        "C2'-C1'-N1": 113.7,
        "C2'-C1'-N9": 113.7,
        "C2'-C3'-C4'": 104.1,
        "C3'-C4'-O4'": 106.0,
        "C3'-O3'-P+": 119.0,
        "C4'-C3'-O3'": 108.9,
        "C4'-O4'-C1'": 109.8,
        "C5'-C4'-C3'": 115.8,
        "C5'-C4'-O4'": 110.0,
        "O1P-P-O2P": 116.1,
        "O1P-P-O5'": 109.6,
        "O2P-P-O5'": 109.6,
        "O3'-P-O1P": 109.6,
        "O3'-P-O2P": 109.6,
        "O3'-P-O5'": 101.4,
        "O4'-C1'-C2'": 105.1,
        "O4'-C1'-N1": 108.6,
        "O4'-C1'-N9": 108.6,
        "O5'-C5'-C4'": 110.0,
        "P-O5'-C5'": 119.0,
    },
    "sugar_pucker": {
        "P": -29.9,
        "tau_m": 36.2,
    },
}

INTERNAL_COORDS = {
    "B": B_DNA_PARAMS,
    "A": A_DNA_PARAMS,
    "Z": {"pos1": Z_DNA_POS1_PARAMS, "pos2": Z_DNA_POS2_PARAMS},
}

# =============================================================================
# Cross-strand Z-matrix parameters for Watson-Crick base pairing
# =============================================================================
# These define how to place strand 2's C1' (and sugar frame) relative to
# strand 1's base atoms using Z-matrix operations.
#
# For purines (A, G) on strand 1: use N1 as the H-bond reference
#   C1'(s2) placed from: N1(s1), angle ref C2(s1), dihedral ref C6(s1)
#
# For pyrimidines (T, C) on strand 1: use N3 as the H-bond reference
#   C1'(s2) placed from: N3(s1), angle ref C2(s1), dihedral ref C4(s1)
#
# Then O4'(s2) and C2'(s2) are placed from C1'(s2) using the H-bond
# atom and its neighbor as references.

B_CROSS_STRAND = {
    # Purine on s1 -> pyrimidine on s2
    # ref_atom = N1(s1), angle_ref = C2(s1), dihedral_ref = C6(s1)
    "A->T": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.115, "C1'_angle": 96.1, "C1'_dihedral": -175.0,
        "O4'_angle": 109.8, "O4'_dihedral": 98.8,   # from ref_atom-C1'-O4'
        "C2'_angle": 140.6, "C2'_dihedral": -109.9,  # from ref_atom-C1'-C2'
    },
    "G->C": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.112, "C1'_angle": 95.0, "C1'_dihedral": -174.9,
        "O4'_angle": 109.9, "O4'_dihedral": 98.7,
        "C2'_angle": 140.8, "C2'_dihedral": -108.8,
    },
    # Pyrimidine on s1 -> purine on s2
    # ref_atom = N3(s1), angle_ref = C2(s1), dihedral_ref = C4(s1)
    "T->A": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.976, "C1'_angle": 108.6, "C1'_dihedral": -175.9,
        "O4'_angle": 108.8, "O4'_dihedral": 97.7,
        "C2'_angle": 142.0, "C2'_dihedral": -109.9,
    },
    "C->G": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.911, "C1'_angle": 111.4, "C1'_dihedral": -175.8,
        "O4'_angle": 108.9, "O4'_dihedral": 97.4,
        "C2'_angle": 142.0, "C2'_dihedral": -109.9,
    },
}

A_CROSS_STRAND = {
    # Purine on s1 -> pyrimidine on s2
    # ref_atom = N1(s1), angle_ref = C2(s1), dihedral_ref = C6(s1)
    "A->T": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.103, "C1'_angle": 96.5, "C1'_dihedral": -176.4,
        "O4'_angle": 142.7, "O4'_dihedral": 153.5,
        "C2'_angle": 105.1, "C2'_dihedral": -61.8,
    },
    "G->C": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.111, "C1'_angle": 94.6, "C1'_dihedral": -176.4,
        "O4'_angle": 143.2, "O4'_dihedral": 153.3,
        "C2'_angle": 104.9, "C2'_dihedral": -61.5,
    },
    # Pyrimidine on s1 -> purine on s2
    # ref_atom = N3(s1), angle_ref = C2(s1), dihedral_ref = C4(s1)
    "T->A": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.977, "C1'_angle": 108.4, "C1'_dihedral": -177.1,
        "O4'_angle": 143.1, "O4'_dihedral": 151.5,
        "C2'_angle": 105.4, "C2'_dihedral": -61.9,
    },
    "C->G": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.911, "C1'_angle": 111.1, "C1'_dihedral": -177.1,
        "O4'_angle": 143.2, "O4'_dihedral": 151.3,
        "C2'_angle": 105.3, "C2'_dihedral": -62.0,
    },
}

# Z-DNA cross-strand parameters (position-specific)
# Z-DNA has alternating conformations, so the cross-strand placement
# depends on the position type of the strand 2 residue.
# In the builder: s2_pos = (n_bp - 1 - i) % 2
#   POS1 (s2_pos=0): s1=C(anti,pos2), s2=G(syn,C3'-endo) — e.g. A:4(C)->B:9(G)
#   POS2 (s2_pos=1): s1=G(syn,pos1), s2=C(anti,C2'-endo) — e.g. A:3(G)->B:10(C)
# Extracted from 3DNA Model 15 (poly d(GC)).

Z_CROSS_STRAND_POS1 = {
    # s2_pos=0: s2 is syn purine (G) with C3'-endo sugar
    # Measured from Model 15: C(s1)->G(s2) pairs
    "A->T": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.104, "C1'_angle": 93.9, "C1'_dihedral": 177.2,
        "O4'_angle": 85.8, "O4'_dihedral": -61.8,
        "C2'_angle": 91.9, "C2'_dihedral": 46.3,
    },
    "C->G": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.921, "C1'_angle": 111.2, "C1'_dihedral": 177.7,
        "O4'_angle": 85.8, "O4'_dihedral": -61.8,
        "C2'_angle": 91.9, "C2'_dihedral": 46.3,
    },
    "G->C": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.199, "C1'_angle": 91.8, "C1'_dihedral": 177.2,
        "O4'_angle": 85.8, "O4'_dihedral": -61.8,
        "C2'_angle": 91.9, "C2'_dihedral": 46.3,
    },
    "T->A": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 8.004, "C1'_angle": 105.9, "C1'_dihedral": 177.8,
        "O4'_angle": 85.8, "O4'_dihedral": -61.8,
        "C2'_angle": 91.9, "C2'_dihedral": 46.3,
    },
}

Z_CROSS_STRAND_POS2 = {
    # s2_pos=1: s2 is anti pyrimidine (C) with C2'-endo sugar
    # Measured from Model 15: G(s1)->C(s2) pairs
    "A->T": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.019, "C1'_angle": 96.7, "C1'_dihedral": 177.2,
        "O4'_angle": 140.5, "O4'_dihedral": 131.0,
        "C2'_angle": 108.5, "C2'_dihedral": -82.0,
    },
    "C->G": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.842, "C1'_angle": 113.6, "C1'_dihedral": 177.6,
        "O4'_angle": 140.5, "O4'_dihedral": 131.0,
        "C2'_angle": 108.5, "C2'_dihedral": -82.0,
    },
    "G->C": {
        "ref_atom": "N1", "angle_ref": "C2", "dihedral_ref": "C6",
        "C1'_dist": 6.110, "C1'_angle": 94.5, "C1'_dihedral": 177.2,
        "O4'_angle": 140.5, "O4'_dihedral": 131.0,
        "C2'_angle": 108.5, "C2'_dihedral": -82.0,
    },
    "T->A": {
        "ref_atom": "N3", "angle_ref": "C2", "dihedral_ref": "C4",
        "C1'_dist": 7.926, "C1'_angle": 108.1, "C1'_dihedral": 177.7,
        "O4'_angle": 140.5, "O4'_dihedral": 131.0,
        "C2'_angle": 108.5, "C2'_dihedral": -82.0,
    },
}

# Form-specific backbone dihedrals for _build_sugar_and_backbone_from_c1
# These are used when building strand 2 outward from the sugar frame.
# Extracted from Colin's 3DNA structures.
STRAND2_BACKBONE_DIHEDRALS = {
    "B": {
        "C2'-C4'-C3'-O3'": 115.9,   # for O3' placement from C3'
        "O4'-C3'-C4'-C5'": 123.8,   # for C5' placement from C4'
    },
    "A": {
        "C2'-C4'-C3'-O3'": 121.6,   # for O3' placement from C3'
        "O4'-C3'-C4'-C5'": 119.2,   # for C5' placement from C4'
    },
    "Z": {
        "C2'-C4'-C3'-O3'": 119.1,   # for O3' placement from C3'
        "O4'-C3'-C4'-C5'": 120.9,   # for C5' placement from C4'
    },
    "Z_pos1": {
        "C2'-C4'-C3'-O3'": 116.2,   # anti/C2'-endo position (strand 2 at pos1)
        "O4'-C3'-C4'-C5'": 122.2,
    },
    "Z_pos2": {
        "C2'-C4'-C3'-O3'": 122.1,   # syn/C3'-endo position (strand 2 at pos2)
        "O4'-C3'-C4'-C5'": 119.5,
    },
}

# Base atom templates (relative coordinates from first structure)
# Used to place base atoms relative to the sugar

B_BASE_TEMPLATES = {
    "A": {
        "atoms": {
            "C2": [-8.438, 1.087, 2.126],
            "C4": [-8.307, 3.163, 1.432],
            "C5": [-8.267, 2.788, 0.120],
            "C6": [-8.321, 1.411, -0.154],
            "C8": [-8.166, 4.901, 0.126],
            "N1": [-8.407, 0.574, 0.897],
            "N3": [-8.394, 2.346, 2.502],
            "N6": [-8.290, 0.901, -1.393],
            "N7": [-8.176, 3.903, -0.702],
            "N9": [-8.242, 4.532, 1.438],
        },
        "C1'": [-8.254, 5.404, 2.645],
        "O4'": [-9.578, 5.877, 2.835],
        "C2'": [-7.397, 6.658, 2.505],
    },
    "T": {
        "atoms": {
            "C2": [1.925, -1.769, 2.523],
            "C4": [2.269, 0.635, 2.941],
            "C5": [2.476, 0.294, 4.328],
            "C5M": [2.770, 1.415, 5.282],
            "C6": [2.404, -0.982, 4.740],
            "N1": [2.134, -1.998, 3.861],
            "N3": [2.004, -0.448, 2.127],
            "O2": [1.684, -2.661, 1.727],
            "O4": [2.316, 1.774, 2.471],
        },
        "C1'": [2.058, -3.411, 4.328],
        "O4'": [0.765, -3.626, 4.871],
        "C2'": [3.027, -3.737, 5.460],
    },
    "G": {
        "atoms": {
            "C2": [1.549, -1.642, 0.390],
            "C4": [1.919, -1.515, 2.589],
            "C5": [2.076, -0.149, 2.607],
            "C6": [1.961, 0.579, 1.394],
            "C8": [2.329, -0.799, 4.617],
            "N1": [1.690, -0.270, 0.311],
            "N2": [1.291, -2.273, -0.758],
            "N3": [1.656, -2.324, 1.530],
            "N7": [2.337, 0.299, 3.901],
            "N9": [2.082, -1.942, 3.890],
            "O6": [2.067, 1.788, 1.208],
        },
        "C1'": [1.999, -3.355, 4.355],
        "O4'": [0.699, -3.570, 4.881],
        "C2'": [2.953, -3.681, 5.501],
    },
    "C": {
        "atoms": {
            "C2": [-1.435, 0.219, 3.335],
            "C4": [-1.217, 2.320, 2.320],
            "C5": [-1.026, 2.959, 3.589],
            "C6": [-1.052, 2.163, 4.688],
            "N1": [-1.251, 0.821, 4.578],
            "N3": [-1.412, 0.999, 2.224],
            "N4": [-1.203, 3.037, 1.207],
            "O2": [-1.612, -1.003, 3.285],
        },
        "C1'": [-1.279, -0.052, 5.784],
        "O4'": [-2.576, 0.025, 6.354],
        "C2'": [-0.329, 0.397, 6.889],
    },
}

A_BASE_TEMPLATES = {
    "A": {
        "atoms": {
            "C2": [-8.791, 2.986, 1.188],
            "C4": [-7.857, 4.959, 1.397],
            "C5": [-7.039, 4.753, 0.322],
            "C6": [-7.155, 3.524, -0.344],
            "C8": [-6.578, 6.687, 1.048],
            "N1": [-8.061, 2.646, 0.128],
            "N3": [-8.772, 4.099, 1.889],
            "N6": [-6.416, 3.188, -1.412],
            "N7": [-6.230, 5.861, 0.110],
            "N9": [-7.568, 6.209, 1.876],
        },
        "C1'": [-8.213, 6.870, 3.046],
        "O4'": [-8.063, 8.274, 2.925],
        "C2'": [-7.580, 6.499, 4.383],
    },
    "T": {
        "atoms": {
            "C2": [1.141, -3.541, 2.382],
            "C4": [1.002, -1.101, 2.698],
            "C5": [0.625, -1.369, 4.066],
            "C5M": [0.353, -0.191, 4.953],
            "C6": [0.525, -2.630, 4.516],
            "N1": [0.777, -3.700, 3.697],
            "N3": [1.235, -2.234, 1.946],
            "O2": [1.369, -4.480, 1.639],
            "O4": [1.119, 0.020, 2.196],
        },
        "C1'": [0.663, -5.096, 4.206],
        "O4'": [-0.192, -5.107, 5.337],
        "C2'": [1.987, -5.683, 4.683],
    },
    "G": {
        "atoms": {
            "C2": [1.729, -3.521, 0.286],
            "C4": [1.116, -3.275, 2.419],
            "C5": [1.097, -1.901, 2.382],
            "C6": [1.428, -1.234, 1.173],
            "C8": [0.545, -2.446, 4.363],
            "N1": [1.737, -2.146, 0.154],
            "N2": [2.053, -4.216, -0.806],
            "N3": [1.419, -4.145, 1.419],
            "N7": [0.734, -1.381, 3.622],
            "N9": [0.759, -3.636, 3.700],
            "O6": [1.468, -0.028, 0.946],
        },
        "C1'": [0.643, -5.031, 4.208],
        "O4'": [-0.218, -5.043, 5.335],
        "C2'": [1.964, -5.619, 4.692],
    },
    "C": {
        "atoms": {
            "C2": [-2.922, -1.830, 3.323],
            "C4": [-2.235, 0.296, 2.616],
            "C5": [-2.546, 0.866, 3.894],
            "C6": [-3.041, 0.026, 4.837],
            "N1": [-3.230, -1.294, 4.571],
            "N3": [-2.424, -1.006, 2.365],
            "N4": [-1.748, 1.057, 1.649],
            "O2": [-3.110, -3.036, 3.129],
        },
        "C1'": [-3.775, -2.217, 5.608],
        "O4'": [-4.498, -1.461, 6.564],
        "C2'": [-2.699, -2.958, 6.394],
    },
}

# Z-DNA base templates are position-specific because purines and pyrimidines
# have different sugar conformations at each position.
# Extracted from 3DNA Model 15 (poly d(GC)) fiber structure.
# Model 15 gives 0.965 Å RMSD vs 1DCG crystal (improved from 1.065 Å Model 16).

Z_BASE_TEMPLATES_POS1 = {
    "G": {
        "atoms": {
            "N9": [-2.381, -6.979, -20.036],
            "C8": [-1.522, -8.043, -19.875],
            "N7": [-0.260, -7.699, -19.776],
            "C5": [-0.287, -6.309, -19.880],
            "C6": [0.776, -5.371, -19.844],
            "O6": [1.980, -5.575, -19.711],
            "N1": [0.305, -4.057, -19.985],
            "C2": [-1.020, -3.699, -20.140],
            "N2": [-1.264, -2.392, -20.259],
            "N3": [-2.016, -4.581, -20.174],
            "C4": [-1.577, -5.860, -20.038],
        },
        "C1'": [-3.865, -6.980, -20.181],
        "O4'": [-4.184, -6.364, -21.418],
        "C2'": [-4.589, -6.222, -19.073],
    },
    "A": {
        "atoms": {
            "N9": [-2.423, -6.916, -20.045],
            "C8": [-1.508, -7.978, -19.879],
            "N7": [-0.217, -7.644, -19.777],
            "C5": [-0.297, -6.373, -19.876],
            "C6": [0.714, -5.400, -19.848],
            "N6": [1.990, -5.760, -19.697],
            "N1": [0.387, -4.107, -19.974],
            "C2": [-0.911, -3.818, -20.121],
            "N3": [-1.912, -4.688, -20.156],
            "C4": [-1.582, -5.978, -20.031],
        },
        "C1'": [-3.865, -6.980, -20.181],
        "O4'": [-4.184, -6.364, -21.418],
        "C2'": [-4.589, -6.222, -19.073],
    },
    "C": {
        "atoms": {
            "N1": [-2.381, -6.979, -20.036],
            "C2": [-3.689, -7.222, -19.690],
            "O2": [-3.886, -7.781, -18.614],
            "N3": [-4.653, -6.836, -20.541],
            "C4": [-4.378, -6.231, -21.698],
            "N4": [-5.366, -5.869, -22.504],
            "C5": [-3.050, -5.975, -22.067],
            "C6": [-2.110, -6.357, -21.227],
        },
        "C1'": [-3.865, -6.980, -20.181],
        "O4'": [-4.184, -6.364, -21.418],
        "C2'": [-4.589, -6.222, -19.073],
    },
    "T": {
        "atoms": {
            "N1": [-2.381, -6.979, -20.036],
            "C2": [-3.689, -7.222, -19.690],
            "O2": [-3.886, -7.781, -18.614],
            "N3": [-4.653, -6.836, -20.541],
            "C4": [-4.378, -6.231, -21.698],
            "O4": [-5.366, -5.869, -22.504],
            "C5": [-3.050, -5.975, -22.067],
            "C5M": [-2.760, -5.297, -23.368],
            "C6": [-2.110, -6.357, -21.227],
        },
        "C1'": [-3.865, -6.980, -20.181],
        "O4'": [-4.184, -6.364, -21.418],
        "C2'": [-4.589, -6.222, -19.073],
    },
}

Z_BASE_TEMPLATES_POS2 = {
    "C": {
        "atoms": {
            "N1": [-1.706, -2.267, -16.324],
            "C2": [-0.349, -1.959, -16.331],
            "O2": [-0.007, -0.771, -16.360],
            "N3": [0.551, -2.976, -16.306],
            "C4": [0.140, -4.250, -16.276],
            "N4": [1.056, -5.205, -16.253],
            "C5": [-1.252, -4.588, -16.268],
            "C6": [-2.135, -3.557, -16.293],
        },
        "C1'": [-2.659, -1.155, -16.351],
        "O4'": [-3.869, -1.596, -15.756],
        "C2'": [-3.045, -0.713, -17.759],
    },
    "T": {
        "atoms": {
            "N1": [-1.698, -2.257, -16.325],
            "C2": [-0.355, -1.962, -16.331],
            "O2": [-0.045, -0.773, -16.360],
            "N3": [0.518, -2.981, -16.307],
            "C4": [0.122, -4.255, -16.276],
            "O4": [1.024, -5.225, -16.253],
            "C5": [-1.244, -4.574, -16.269],
            "C5M": [-1.669, -6.006, -16.235],
            "C6": [-2.094, -3.568, -16.293],
        },
        "C1'": [-2.659, -1.155, -16.351],
        "O4'": [-3.869, -1.596, -15.756],
        "C2'": [-3.045, -0.713, -17.759],
    },
    "A": {
        "atoms": {
            "N9": [-1.706, -2.267, -16.324],
            "C8": [-1.364, -3.598, -15.998],
            "N7": [-2.311, -4.328, -15.401],
            "C5": [-3.260, -3.475, -15.342],
            "C6": [-4.557, -3.603, -14.821],
            "N6": [-4.955, -4.757, -14.283],
            "N1": [-5.392, -2.556, -14.870],
            "C2": [-4.927, -1.430, -15.423],
            "N3": [-3.716, -1.245, -15.932],
            "C4": [-2.885, -2.293, -15.882],
        },
        "C1'": [-2.659, -1.155, -16.351],
        "O4'": [-3.869, -1.596, -15.756],
        "C2'": [-3.045, -0.713, -17.759],
    },
    "G": {
        "atoms": {
            "N9": [-1.706, -2.267, -16.324],
            "C8": [-1.364, -3.598, -15.998],
            "N7": [-2.311, -4.328, -15.401],
            "C5": [-3.260, -3.475, -15.342],
            "C6": [-4.557, -3.603, -14.821],
            "O6": [-4.955, -4.757, -14.283],
            "N1": [-5.392, -2.556, -14.870],
            "C2": [-4.927, -1.430, -15.423],
            "N2": [-5.768, -0.380, -15.470],
            "N3": [-3.716, -1.245, -15.932],
            "C4": [-2.885, -2.293, -15.882],
        },
        "C1'": [-2.659, -1.155, -16.351],
        "O4'": [-3.869, -1.596, -15.756],
        "C2'": [-3.045, -0.713, -17.759],
    },
}

# Legacy alias for backward compatibility
Z_BASE_TEMPLATES = Z_BASE_TEMPLATES_POS1

# =============================================================================
# Base internal coordinates for Z-matrix base growth
# =============================================================================
# These define how to grow base atoms atom-by-atom from the sugar.
# Each entry is (atom_to_place, ref1, ref2, ref3, distance, angle, dihedral)
# where the new atom is placed at:
#   distance from ref1, angle at ref1 (ref2-ref1-new), dihedral ref3-ref2-ref1-new

# Base internal coordinates for Z-matrix base growth.
# Each growth step: (new_atom, ref1, ref2, ref3, dist, angle, dihedral)
# place_atom(dist, angle, dihedral, ref1, ref2, ref3) places new atom at:
#   distance from ref1, angle ref2-ref1-new, dihedral ref3-ref2-ref1-new
#
# Step 1: Place N9/N1 from C1' using dihedral C2'-O4'-C1'-N (~122°)
# Step 2: Place C4/C2 from N9/N1 using chi dihedral (O4'-C1'-N9-C4 or O4'-C1'-N1-C2)
# Remaining steps use ring-closure dihedrals (~0° or ~180° for planar bases)

BASE_GROWTH_IC = {
    "A": {  # Adenine (purine)
        "glycosidic_atom": "N9",
        "growth": [
            # (new_atom, ref1, ref2, ref3, dist, angle, dihedral)
            # Step 1: N9 from C1', dihedral = C2'-O4'-C1'-N9
            ("N9",  "C1'", "O4'", "C2'", 1.531, 107.1, 121.9),
            # Step 2: C4 from N9, dihedral = O4'-C1'-N9-C4 = chi (set by caller)
            ("C4",  "N9",  "C1'", "O4'", 1.375, 126.5, None),
            # Ring atoms (planar, dihedrals ~0 or ~180)
            ("C8",  "N9",  "C1'", "C4",  1.375, 127.7, 179.9),
            ("N7",  "C8",  "N9",  "C1'", 1.310, 113.8, -180.0),
            ("N3",  "C4",  "N9",  "C1'", 1.344, 127.4, -0.1),
            ("C5",  "C4",  "N9",  "C8",  1.384, 105.7, 0.1),
            ("C6",  "C5",  "C4",  "N3",  1.406, 117.0, 0.1),
            ("N1",  "C6",  "C5",  "C4",  1.351, 117.6, -0.1),
            ("C2",  "N1",  "C6",  "C5",  1.338, 118.6, 0.1),
            ("N6",  "C6",  "C5",  "N1",  1.334, 123.8, -179.9),
        ],
    },
    "G": {  # Guanine (purine)
        "glycosidic_atom": "N9",
        "growth": [
            ("N9",  "C1'", "O4'", "C2'", 1.502, 107.9, 123.4),
            ("C4",  "N9",  "C1'", "O4'", 1.374, 124.9, None),
            ("C8",  "N9",  "C1'", "C4",  1.375, 128.8, -179.8),
            ("N7",  "C8",  "N9",  "C1'", 1.305, 113.1, 180.0),
            ("N3",  "C4",  "N9",  "C1'", 1.350, 126.0, 0.1),
            ("C5",  "C4",  "N9",  "C8",  1.380, 105.5, -0.1),
            ("C6",  "C5",  "C4",  "N3",  1.418, 118.9, -0.1),
            ("N1",  "C6",  "C5",  "C4",  1.390, 111.7, 0.1),
            ("C2",  "N1",  "C6",  "C5",  1.374, 125.0, -0.1),
            ("O6",  "C6",  "C5",  "N1",  1.238, 128.4, 180.0),
            ("N2",  "C2",  "N1",  "C6",  1.342, 116.1, -179.9),
        ],
    },
    "T": {  # Thymine (pyrimidine)
        "glycosidic_atom": "N1",
        "growth": [
            ("N1",  "C1'", "O4'", "C2'", 1.487, 109.2, 122.3),
            ("C2",  "N1",  "C1'", "O4'", 1.377, 119.7, None),
            ("C6",  "N1",  "C1'", "C2",  1.377, 119.1, -180.0),
            ("N3",  "C2",  "N1",  "C1'", 1.372, 114.6, 180.0),
            ("O2",  "C2",  "N1",  "N3",  1.220, 123.0, -180.0),
            ("C4",  "N3",  "C2",  "N1",  1.382, 127.3, 0.1),
            ("C5",  "C4",  "N3",  "C2",  1.446, 115.2, -0.1),
            ("O4",  "C4",  "N3",  "C5",  1.227, 120.0, -179.9),
            ("C5M", "C5",  "C4",  "C6",  1.497, 119.1, 180.0),
        ],
    },
    "C": {  # Cytosine (pyrimidine)
        "glycosidic_atom": "N1",
        "growth": [
            ("N1",  "C1'", "O4'", "C2'", 1.462, 108.0, 121.7),
            ("C2",  "N1",  "C1'", "O4'", 1.397, 118.2, None),
            ("C6",  "N1",  "C1'", "C2",  1.367, 121.6, -180.0),
            ("N3",  "C2",  "N1",  "C1'", 1.353, 119.3, -179.9),
            ("O2",  "C2",  "N1",  "N3",  1.240, 118.9, 180.0),
            ("C4",  "N3",  "C2",  "N1",  1.336, 119.9, -0.1),
            ("C5",  "C4",  "N3",  "C2",  1.423, 121.9, 0.1),
            ("N4",  "C4",  "N3",  "C5",  1.336, 117.8, 179.9),
        ],
    },
}
