"""
PDB file output for DNA structures.

Writes atoms in standard PDB ATOM record format with proper column alignment,
chain IDs, residue numbering, and element symbols.
Also supports XYZ, mmCIF, and CML output formats.
"""

from typing import List, TextIO
from .builder import Atom


def format_atom_name(name: str, element: str) -> str:
    """Format atom name for PDB columns 13-16."""
    if len(name) >= 4:
        return name[:4]
    if len(element) == 1:
        return f" {name:<3s}"
    else:
        return f"{name:<4s}"


def write_pdb(atoms: List[Atom], output, title: str = "DNA structure"):
    """Write atoms to a PDB file."""
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_pdb_records(atoms, f, title)
    else:
        _write_pdb_records(atoms, output, title)


def _write_pdb_records(atoms: List[Atom], f: TextIO, title: str):
    """Write PDB records to a file object."""
    f.write(f"TITLE     {title}\n")
    f.write(f"REMARK    Generated by DNA Builder\n")
    f.write(f"REMARK    Using canonical fiber diffraction coordinates\n")

    prev_chain = None
    prev_atom = None
    serial = 0

    for atom in atoms:
        serial += 1

        # Write TER record between chains
        if prev_chain is not None and atom.chain_id != prev_chain and prev_atom is not None:
            f.write(f"TER   {serial:>5d}      "
                    f"{prev_atom.residue_name:>3s} "
                    f"{prev_chain}"
                    f"{prev_atom.residue_seq:>4d}\n")
            serial += 1

        atom_name = format_atom_name(atom.name, atom.element)

        line = (
            f"ATOM  {serial:>5d} {atom_name}"
            f" {atom.residue_name:>3s} "
            f"{atom.chain_id}"
            f"{atom.residue_seq:>4d}    "
            f"{atom.x:>8.3f}{atom.y:>8.3f}{atom.z:>8.3f}"
            f"  1.00  0.00          "
            f"{atom.element:>2s}\n"
        )
        f.write(line)
        prev_chain = atom.chain_id
        prev_atom = atom

    # Final TER
    if prev_atom is not None:
        serial += 1
        f.write(f"TER   {serial:>5d}      "
                f"{prev_atom.residue_name:>3s} "
                f"{prev_atom.chain_id}"
                f"{prev_atom.residue_seq:>4d}\n")

    f.write("END\n")


def write_xyz(atoms: List[Atom], output, comment: str = "DNA structure"):
    """Write atoms in XYZ format."""
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_xyz_records(atoms, f, comment)
    else:
        _write_xyz_records(atoms, output, comment)


def _write_xyz_records(atoms: List[Atom], f: TextIO, comment: str):
    """Write XYZ records to a file object."""
    f.write(f"{len(atoms)}\n")
    f.write(f"{comment}\n")
    for atom in atoms:
        f.write(f"{atom.element:<2s}  {atom.x:>12.6f}  {atom.y:>12.6f}  "
                f"{atom.z:>12.6f}\n")


def write_cml(atoms: List[Atom], output, title: str = "DNA structure"):
    """Write atoms in Chemical Markup Language (CML) format."""
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_cml_records(atoms, f, title)
    else:
        _write_cml_records(atoms, output, title)


def _write_cml_records(atoms: List[Atom], f: TextIO, title: str):
    """Write CML records to a file object."""
    f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    f.write('<molecule xmlns="http://www.xml-cml.org/schema">\n')
    f.write(f'  <name>{title}</name>\n')
    f.write('  <atomArray>\n')

    for i, atom in enumerate(atoms, 1):
        f.write(
            f'    <atom id="a{i}" elementType="{atom.element}" '
            f'x3="{atom.x:.6f}" y3="{atom.y:.6f}" z3="{atom.z:.6f}" '
            f'residue="{atom.residue_name}" '
            f'chainId="{atom.chain_id}" '
            f'residueSeq="{atom.residue_seq}"/>\n'
        )

    f.write('  </atomArray>\n')
    f.write('</molecule>\n')


def write_mmcif(atoms: List[Atom], output, title: str = "DNA structure"):
    """Write atoms in mmCIF format (PDBx/mmCIF)."""
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_mmcif_records(atoms, f, title)
    else:
        _write_mmcif_records(atoms, output, title)


def _cif_name(name: str) -> str:
    """Quote CIF atom name if it contains special characters (e.g. O5')."""
    if any(c in name for c in ("'", '"', ' ', '\t')):
        return f'"{name}"'
    return name


def _write_mmcif_records(atoms: List[Atom], f: TextIO, title: str):
    """Write mmCIF records to a file object."""
    safe_title = title.replace("'", "")
    f.write("data_DNA_BUILDER\n")
    f.write("#\n")
    f.write(f"_entry.id                         DNA_BUILDER\n")
    f.write(f"_struct.title                     '{safe_title}'\n")
    f.write("#\n")
    f.write("loop_\n")
    f.write("_atom_site.group_PDB\n")
    f.write("_atom_site.id\n")
    f.write("_atom_site.type_symbol\n")
    f.write("_atom_site.label_atom_id\n")
    f.write("_atom_site.label_comp_id\n")
    f.write("_atom_site.label_asym_id\n")
    f.write("_atom_site.label_seq_id\n")
    f.write("_atom_site.Cartn_x\n")
    f.write("_atom_site.Cartn_y\n")
    f.write("_atom_site.Cartn_z\n")
    f.write("_atom_site.occupancy\n")
    f.write("_atom_site.B_iso_or_equiv\n")
    f.write("_atom_site.auth_asym_id\n")
    f.write("_atom_site.auth_seq_id\n")
    f.write("_atom_site.auth_atom_id\n")
    f.write("_atom_site.pdbx_PDB_model_num\n")

    for i, atom in enumerate(atoms, 1):
        name = _cif_name(atom.name)
        chain = atom.chain_id or "A"
        f.write(
            f"ATOM  {i:>6d} {atom.element:>2s} {name:<6s} "
            f"{atom.residue_name:>3s} {chain:>2s} {atom.residue_seq:>4d} "
            f"{atom.x:>8.3f} {atom.y:>8.3f} {atom.z:>8.3f} "
            f"1.00 0.00 "
            f"{chain:>2s} {atom.residue_seq:>4d} {name:<6s} 1\n"
        )

    f.write("#\n")
