"""
PDB file output for DNA structures.

Writes atoms in standard PDB ATOM record format with proper column alignment,
chain IDs, residue numbering, and element symbols.

PDB format specification:
  Columns  1- 6: Record type "ATOM  "
  Columns  7-11: Atom serial number
  Columns 13-16: Atom name
  Column  17:    Alternate location indicator
  Columns 18-20: Residue name
  Column  22:    Chain ID
  Columns 23-26: Residue sequence number
  Column  27:    Code for insertion of residues
  Columns 31-38: X coordinate (8.3)
  Columns 39-46: Y coordinate (8.3)
  Columns 47-54: Z coordinate (8.3)
  Columns 55-60: Occupancy (6.2)
  Columns 61-66: Temperature factor (6.2)
  Columns 77-78: Element symbol
  Columns 79-80: Charge
"""

from typing import List, TextIO
import sys
from .builder import Atom


def format_atom_name(name: str, element: str) -> str:
    """
    Format atom name for PDB columns 13-16.

    PDB convention:
    - 1-character element symbols start in column 14 (right-justified in 13-14)
    - 2-character element symbols start in column 13
    - Atom name is left-justified in remaining columns

    For DNA atoms, most are 1-character elements (C, N, O, P, H).
    """
    if len(name) >= 4:
        return name[:4]
    if len(element) == 1:
        # Right-justify element in columns 13-14, then atom name continues
        return f" {name:<3s}"
    else:
        return f"{name:<4s}"


def write_pdb(atoms: List[Atom], output, title: str = "DNA structure"):
    """
    Write atoms to a PDB file.

    Parameters
    ----------
    atoms : List[Atom]
        List of atoms to write.
    output : str or file-like
        Output filename (str) or file-like object.
    title : str
        Title for the TITLE record.
    """
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_pdb_records(atoms, f, title)
    else:
        _write_pdb_records(atoms, output, title)


def _write_pdb_records(atoms: List[Atom], f: TextIO, title: str):
    """Write PDB records to a file object."""
    f.write(f"TITLE     {title}\n")
    f.write(f"REMARK    Generated by DNA Builder\n")
    f.write(f"REMARK    Using canonical fiber diffraction coordinates\n")

    prev_chain = None
    serial = 0

    for atom in atoms:
        serial += 1

        # Write TER record between chains
        if prev_chain is not None and atom.chain_id != prev_chain:
            f.write(f"TER   {serial:>5d}      "
                    f"{atoms[serial-2].residue_name:>3s} "
                    f"{prev_chain}"
                    f"{atoms[serial-2].residue_seq:>4d}\n")
            serial += 1

        atom_name = format_atom_name(atom.name, atom.element)

        line = (
            f"ATOM  {serial:>5d} {atom_name}"
            f" {atom.residue_name:>3s} "
            f"{atom.chain_id}"
            f"{atom.residue_seq:>4d}    "
            f"{atom.x:>8.3f}{atom.y:>8.3f}{atom.z:>8.3f}"
            f"  1.00  0.00          "
            f"{atom.element:>2s}\n"
        )
        f.write(line)
        prev_chain = atom.chain_id

    # Final TER
    serial += 1
    if atoms:
        last = atoms[-1]
        f.write(f"TER   {serial:>5d}      "
                f"{last.residue_name:>3s} "
                f"{last.chain_id}"
                f"{last.residue_seq:>4d}\n")

    f.write("END\n")


def write_xyz(atoms: List[Atom], output, comment: str = "DNA structure"):
    """
    Write atoms in XYZ format.

    Parameters
    ----------
    atoms : List[Atom]
        List of atoms to write.
    output : str or file-like
        Output filename or file-like object.
    comment : str
        Comment line.
    """
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_xyz_records(atoms, f, comment)
    else:
        _write_xyz_records(atoms, output, comment)


def _write_xyz_records(atoms: List[Atom], f: TextIO, comment: str):
    """Write XYZ records to a file object."""
    f.write(f"{len(atoms)}\n")
    f.write(f"{comment}\n")
    for atom in atoms:
        f.write(f"{atom.element:<2s}  {atom.x:>12.6f}  {atom.y:>12.6f}  "
                f"{atom.z:>12.6f}\n")


def write_cml(atoms: List[Atom], output, title: str = "DNA structure"):
    """
    Write atoms in Chemical Markup Language (CML) format.

    This is a basic CML output with atom coordinates. Bond information
    is not included (would require bond detection).

    Parameters
    ----------
    atoms : List[Atom]
        List of atoms to write.
    output : str or file-like
        Output filename or file-like object.
    title : str
        Molecule title.
    """
    if isinstance(output, str):
        with open(output, "w") as f:
            _write_cml_records(atoms, f, title)
    else:
        _write_cml_records(atoms, output, title)


def _write_cml_records(atoms: List[Atom], f: TextIO, title: str):
    """Write CML records to a file object."""
    f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    f.write('<molecule xmlns="http://www.xml-cml.org/schema">\n')
    f.write(f'  <name>{title}</name>\n')
    f.write('  <atomArray>\n')

    for i, atom in enumerate(atoms, 1):
        f.write(
            f'    <atom id="a{i}" elementType="{atom.element}" '
            f'x3="{atom.x:.6f}" y3="{atom.y:.6f}" z3="{atom.z:.6f}" '
            f'residue="{atom.residue_name}" '
            f'chainId="{atom.chain_id}" '
            f'residueSeq="{atom.residue_seq}"/>\n'
        )

    f.write('  </atomArray>\n')
    f.write('</molecule>\n')
